### ISSUE TITLE
ai not doing anything

### ISSUE THREAD

**Issue by FableRift** [YOUSY0US3F/minecraft-gpt-god-plugin#52]
so i've paid 5 dollars for the ai and put the api key in the plugin config, but when i join the server, god isn't saying or doing anything and in the console, it gives me these warnings:

[15:36:59 WARN]: [gptgodmc] Plugin gptgodmc v0.1.6 generated an exception while executing task 2
java.lang.NullPointerException: Cannot invoke "net.bigyous.gptgodmc.LocalGameMap.getWorld()" because "net.bigyous.gptgodmc.WorldManager.currentGameMap" is null
        at net.bigyous.gptgodmc.WorldManager.getCurrentWorld(WorldManager.java:105) ~[gptgodmc-0.1.7-all.jar:?]
        at net.bigyous.gptgodmc.ServerInfoSummarizer.getStatusSummary(ServerInfoSummarizer.java:123) ~[gptgodmc-0.1.7-all.jar:?]
        at net.bigyous.gptgodmc.EventLogger.cull(EventLogger.java:48) ~[gptgodmc-0.1.7-all.jar:?]
        at net.bigyous.gptgodmc.GameLoop$GPTTask.run(GameLoop.java:104) ~[gptgodmc-0.1.7-all.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by YOUSY0US3F** [comment]
Did you set up the worlds folder?
https://authors.curseforge.com/#/projects/1092626/files
extract `worlds.zip` into `plugins/gptgodmc`

**Comment by FableRift** [comment]
i accidentaly put the island and deathmatch world into plugins/gptgodmc instead of plugins/gptgodmc/worlds, it now works but the console is getting spammed with
[16:36:38 ERROR]: Recoverable errors when loading section [1, 5, -2]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: minecraft:island -> using default)
[16:36:38 ERROR]: Recoverable errors when loading section [1, 6, -2]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: minecraft:island -> using default) etc.
i dont if thats supposed to happen, but thanks.

**Comment by YOUSY0US3F** [comment]
Yeah, thats expected behavior. Minecraft always complains when the map gets loaded
